import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";

const geistFont = localFont({
  src: "./fonts/GeistVariableVF.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistFont.className} bg-almostBlack`}>
      <body className="xl:container">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
