import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { Providers } from "../providers";
import Navbar from "@/components/nav/Navbar";
import Footer from "@/components/sections/Footer";

const geistFont = localFont({
  src: "../fonts/GeistVariableVF.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "DevTalk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistFont.className} bg-almostBlack`}>
      <body className="dark xl:container">
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
